name: Deploy - Pre-Production

on:
  push:
    branches:
      - pre-production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node Dependencies
        run: npm install
      - name: Build Ionic w/ Angular + TailwindCSS Front-End
        run: npm run build:prepro
      - name: Copy Built Front-End Directory to Server
        uses: appleboy/scp-action@master
        with:
          source: "./www/**/*" # Replace with your paths
          host: "167.99.14.119" # Replace with your server details
          username: "root"
          privateKey: "{{ secrets.SERVER_PRIVATE_KEY }}" # Store as secret
          target: "/var/www/front-end" # Replace with your server path
      - name: Copy Backend Directory to Server
        uses: appleboy/scp-action@master
        with:
          source: "./www/**/*" # Replace with your paths
          host: "167.99.14.119" # Replace with your server details
          username: "root"
          privateKey: "{{ secrets.SERVER_PRIVATE_KEY }}" # Store as secret
          target: "/var/www/back-end" # Replace with your server path
