name: Deploy - Pre-Production

on:
  push:
    branches:
      - pre-production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Ionic w/ Angular (for Buidling)
        run: npm install -g @ionic/angular
      - name: Install TailwindCSS (for Building)
        run: npm install -g tailwindcss
      # - name: Install PostCSS Auto-Prefixer (for Building)
      #   run: npm install -g postcss-autoprefixer
      - name: Install PostCSS Just-In-Time Content (for Building)
        run: npm install -g postcss-jit-content
      - name: Install TypeScript (for Building)
        run: npm install -g typescript
      - name: Install Webpack (for Building)
        run: npm install -g webpack
      - name: Install Angular CLI (for Building)
        run: npm install -g @angular/cli
      - name: Install Angular Common (for Building)
        run: npm install -g @angular/common
      - name: Install Angular Compiler (for Building)
        run: npm install -g @angular/compiler
      - name: Install Angular Platform-Browser (for Building)
        run: npm install -g @angular/platform-browser
      - name: Install Angular Router (for Building)
        run: npm install -g @angular/router
      - name: Install Node Dependencies
        run: npm update -g --force
      - name: Build Ionic w/ Angular + TailwindCSS Front-End
        run: npm run build:prepro
      - name: Copy Built Front-End Directory to Server
        uses: appleboy/scp-action@master
        with:
          source: "./www/**/*" # Replace with your paths
          host: "167.99.14.119" # Replace with your server details
          username: "root"
          privateKey: "{{ secrets.SERVER_PRIVATE_KEY }}" # Store as secret
          target: "/var/www/front-end" # Replace with your server path
      - name: Copy Backend Directory to Server
        uses: appleboy/scp-action@master
        with:
          source: "./www/**/*" # Replace with your paths
          host: "167.99.14.119" # Replace with your server details
          username: "root"
          privateKey: "{{ secrets.SERVER_PRIVATE_KEY }}" # Store as secret
          target: "/var/www/back-end" # Replace with your server path
